<?php

/**
 * @package    osFreeLands
 * @copyright Copyright (C) 2013 Wene - ssm2017 Binder ( S.Massiaux ). All rights reserved.
 * @license   GNU/GPL, http://www.gnu.org/licenses/gpl-2.0.html
 * osFreeLands is free software. This version may have been modified pursuant
 * to the GNU General Public License, and as distributed it includes or
 * is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 */

/**
 * Implements hook_menu().
 */
function osfreelands_menu() {
	$items = array();
	$items['admin/config/metaverse-framework/osfreelands'] = array(
		'title' => 'osFreeLands',
		'description' => 'Settings for the osfreelands module.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('osfreelands_settings'),
		'access arguments' => array('administer site configuration'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['osfreelands/terminals/update/%'] = array(
		'title' => 'Update terminal',
		'type' => MENU_CALLBACK,
		'page callback' => 'osfreelands_update_terminal',
		'page arguments' => array(3),
		'access callback' => TRUE,
		'file' => 'osfreelands_terminals.inc'
	);
	$items['osfreelands/parcels/rent/%/%'] = array(
    'title' => 'parcel rent callback',
    'type' => MENU_CALLBACK,
    'page callback' => 'osfreelands_rent_parcel_callback',
    'page arguments' => array(3,4),
    'access callback' => TRUE,
		'file' => 'osfreelands_parcels.inc'
  );
	return $items;
}

/**
 * Admin settings
 */
function osfreelands_settings() {
	// get roles
  $roles = array(
    '0' => t('None'),
  );
  $roles += user_roles(TRUE);

	$form = array();
	// password
	$form['osfreelands_password_fieldset'] = array(
		'#type' => 'fieldset',
		'#title' => t('Password'),
		'#collapsible' => FALSE,
		'#collapsed' => FALSE,
	);
	$form['osfreelands_password_fieldset']['osfreelands_password'] = array(
		'#type' => 'textfield',
		'#title' => t('Password.'),
		'#default_value' => variable_get('osfreelands_password', '1234'),
		'#description' => t("Enter the password to communicate with the boxes."),
	);
	// fieldset
	$form['osfreelands_parcels_fieldset'] = array(
		'#type' => 'fieldset',
		'#title' => t('Parcels'),
		'#collapsible' => FALSE,
		'#collapsed' => FALSE,
	);
	$form['osfreelands_parcels_fieldset']['osfreelands_max_parcels_per_user'] = array(
		'#type' => 'textfield',
		'#title' => t('Max parcels per user.'),
		'#size' => 4,
		'#maxlength' => 4,
		'#default_value' => variable_get('osfreelands_max_parcels_per_user', 0),
		'#description' => t("Maximum quantity of parcels a single user can own. (0 means infinite)"),
	);
	$form['osfreelands_parcels_fieldset']['osfreelands_renting_duration'] = array(
		'#type' => 'textfield',
		'#title' => t('Renting duration.'),
		'#size' => 3,
		'#maxlength' => 3,
		'#default_value' => variable_get('osfreelands_renting_duration', 0),
		'#description' => t("Renting duration in days. (0 means infinite)"),
	);
	// roles
	$form['osfreelands_roles_fieldset'] = array(
		'#type' => 'fieldset',
		'#title' => t('Roles'),
		'#collapsible' => FALSE,
		'#collapsed' => FALSE,
	);
  $form['osfreelands_roles_fieldset']['osfreelands_terminal_role'] = array(
    '#type' => 'select',
    '#title' => t('Terminal owners'),
    '#default_value' => variable_get('osfreelands_terminal_role', 0),
    '#options' => $roles,
    '#description' => t('This role is automatically assigned to terminal owners.'),
  );
	$form['osfreelands_roles_fieldset']['osfreelands_parcel_role'] = array(
    '#type' => 'select',
    '#title' => t('Parcel owners'),
    '#default_value' => variable_get('osfreelands_parcel_role', 0),
    '#options' => $roles,
    '#description' => t('This role is automatically assigned to parcel owners.'),
  );
	return system_settings_form($form);
}

/**
 * Implements hook_permission.
 */
function osfreelands_permission() {
  return array(
    'osfl manage terminals' => array(
      'title' => t('Manage terminals'),
      'description' => t('Allow the user to see and update any terminal.'),
    ),
  );
}

/**
 * Implements hook_views_api.
 */
function osfreelands_views_api() {
  return array(
    'api' => 3
  );
}

/**
 * Implements hook_cron.
 */
function osfreelands_cron() {
	module_load_include('inc', 'osfreelands', 'osfreelands_terminals');
	module_load_include('inc', 'osfreelands', 'osfreelands_parcels');
	// get expired parcels
	$query = new EntityFieldQuery();
	$entities = $query->entityCondition('entity_type', 'node')
			->propertyCondition('type', 'freelands_parcel')
			->fieldCondition('field_osfl_end_time', 'value', time(), '<=')
			->execute();
	if (isset($entities['node'])) {
		foreach ($nodes_ids as $nid) {
			// get the parcel
			$parcel = node_load($nid);
			$old_owner = $parcel->field_osfl_parcel_owner[$parcel->language][0]['uuid_field'];
			// get the terminal
			$terminal = osfreelands_ping_terminal($parcel->field_osfl_term_nid[$parcel->language][0]['target_id']);
			if ($terminal->online_status != 'online') {
				watchdog('freelands', 'Terminal !name is not responding.', array('!name' => $terminal->title), WATCHDOG_ERROR, $link = l($terminal->title, 'node/'.$terminal->nid));
				continue;
			}
			$default_owner = $terminal->field_osfl_term_default_owner[$terminal->language][0]['uuid_field'];
			// get the url
			$url = $terminal->field_osfl_term_url[$terminal->language][0]['value'];
			// tell it inworld
			$response = metaverse_framework_http_request($url . 'reset-parcel?'.urlencode($parcel->field_osfl_parcel_location[$parcel->language][0]['value']));
			if ($response->success && $response->code == 200) {
				$parcel->field_osfl_parcel_status[$parcel->language][0]['value'] = 0;
				$parcel->field_osfl_end_time[$parcel->language][0]['value'] = NULL;
				$parcel->field_osfl_parcel_owner[$parcel->language][0]['uuid_field'] = $default_owner;
				node_save($parcel);
				watchdog('freelands', 'Parcel !name expired.', array('!name' => $parcel->title), WATCHDOG_NOTICE, $link = l($parcel->title, 'node/'.$parcel->nid));
				// get parcels owned by this user
				$owned_parcels = osfreelands_get_parcels_by_owner_key(array('owner_key' => $old_owner));
				// remove the parcel role if no more parcels owned
				if (is_null($owned_parcels)) {
					db_query("DELETE FROM {users_roles} WHERE rid=:rid AND uid=:uid", array(':rid' => $rid, ':uid' => $uid));
				}
			}
			else {
				watchdog('freelands', 'Error changing parcel inworld details.', array(), WATCHDOG_ERROR, $link = l($parcel->title, 'node/'.$parcel->nid));
			}
		}
	}
}

/**
 * Implements hook_node_view.
 */
function osfreelands_node_view($node, $build_mode = 'full') {
	if ($build_mode == 'full') {
		switch ($node->type) {
			case 'freelands_terminal':
				module_load_include('inc', 'osfreelands', 'osfreelands_terminals');
				osfreelands_add_update_terminal_button($node);
				break;
			case 'freelands_parcel':
				module_load_include('inc', 'osfreelands', 'osfreelands_parcels');
				osfreelands_add_rent_parcel_button($node);
				osfreelands_add_parcel_region_name($node);
				break;
		}
	}
}

/**
 * Implements hook_node_delete.
 */
function osfreelands_node_delete($node) {
	if ($node->type == 'freelands_terminal') {
		// delete parcels
		module_load_include('inc', 'osfreelands', 'osfreelands_parcels');
		$parcels_nids = osfreelands_get_parcels_by_terminal_nid(array('terminal_nid' => $node->nid));
		if (!is_null($parcels_nids)) {
			node_delete_multiple($parcels_nids);
		}
	}
}

/**
 * metaverse frameworkd dispatcher
 */
function osfreelands_dispatch($params) {
	$cmd = $params['cmd'];
	$sl = &$params['sl'];
	$args = $params['args'];
	switch ($cmd) {
		case 'save_terminal':
			module_load_include('inc', 'osfreelands', 'osfreelands_terminals');
			osfreelands_inworld_save_terminal($sl, $args);
			break;
		default:
			$sl->response['status'] = FALSE;
			$sl->response['message'] = "Oops! Unknown command: $cmd.";
			break;
	}
}

function osfreelands_set_role($uid, $role) {
  if (!is_numeric($uid)) {
		return;
	}

	switch ($role) {
		case 'terminal':
			$rid = variable_get('osfreelands_terminal_role', 0);
			break;
		case 'parcel':
			$rid = variable_get('osfreelands_parcel_role', 0);
			break;
		default:
			return;
	}

  if ($rid == 0) {
		return;
	}

  // remove assigned roles
  db_query("DELETE FROM {users_roles} WHERE rid=:rid AND uid=:uid", array(':rid' => $rid, ':uid' => $uid));

  // assign the role
  db_query("INSERT INTO {users_roles} (rid, uid) VALUES (:rid, :uid)", array(':rid' => $rid, ':uid' => $uid));
}

function osfreelands_get_uuid_by_uid($uid) {
	$uuid = FALSE;
	if (module_exists('d4os_ui_users')) {
		// get the uid of the terminal owner
		$uuid = db_query("SELECT UUID FROM {d4os_ui_users} WHERE uid = :uid", array(':uid' => $uid))->fetchField();
	}
	else if (module_exists('metaverse_user')) {
		$user = user_load($uid);
		$uuid = isset($user->field_mu_user_uuid[LANGUAGE_NONE][0]['uuid_field']) ? $user->field_mu_user_uuid[LANGUAGE_NONE][0]['uuid_field'] : FALSE;
	}
	return $uuid;
}

function osfreelands_get_uid_by_uuid($uuid) {
	$uid = FALSE;
	if (module_exists('d4os_ui_users')) {
		// get the uid of the terminal owner
		$uid = db_query("SELECT uid FROM {d4os_ui_users} WHERE UUID = :uuid", array(':uuid' => $uuid))->fetchField();
	}
	else if (module_exists('metaverse_user')) {
		$query = new EntityFieldQuery();
		$entities = $query->entityCondition('entity_type', 'user')
				->fieldCondition('field_mu_user_uuid', 'uuid_field', $uuid)
				->execute();
		if (isset($entities['user'])) {
			reset($entities['user']);
			$uid = key($entities['user']);
		}
	}
	return $uid;
}